echo on
md %BUILD_ROOT%
cd %BUILD_ROOT% || exit /b 1
cmake -G "%CMAKE_GENERATOR%" -DYALTA_VERSION_MAJOR=%YALTA_VERSION_MAJOR% -DYALTA_VERSION_MINOR=%YALTA_VERSION_MINOR% -DYALTA_BUILD=%APPVEYOR_BUILD_NUMBER% "%APPVEYOR_BUILD_FOLDER%" || exit /b 1
cmake --build . --config %CONFIGURATION% || exit /b 1
md %PRODUCT_DIR%
move %CONFIGURATION%\* %PRODUCT_DIR% || exit /b 1
7z a yalta-%APPVEYOR_BUILD_VERSION%-%ARCH%.zip %PRODUCT_DIR% || exit /b 1
